spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

jwt:
  expiration: 900000

server:
  port: 8081

user-service:
  url: http://localhost:8080

notification-service:
  url: http://localhost:8082

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG